name: Python application

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb  # Para tests que requieran display

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
          # Instalar dependencias básicas para tu app
          pip install PySide6 cryptography
          # Instalar desde requirements.txt si existe
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Run tests
        env:
          CI: true # Variable para saltar tests de GUI
          DISPLAY: ":99.0" # Display virtual para tests
        run: |
          # Ejecutar tests con display virtual
          xvfb-run -a pytest -v --tb=short

      - name: Check Python syntax
        run: |
          # Verificar sintaxis de archivos Python
          find . -name "*.py" -exec python -m py_compile {} \;
